basePath: /
definitions:
  model.Address:
    properties:
      city:
        example: Metropolis
        type: string
      district:
        example: Central
        type: string
      lane:
        example: 1234 Elm St
        type: string
      pincode:
        example: 123456
        type: integer
      state:
        example: NY
        type: string
      village:
        example: Springfield
        type: string
    required:
    - city
    - district
    - pincode
    - state
    type: object
  model.Name:
    properties:
      first_name:
        example: John
        type: string
      last_name:
        example: Smith
        type: string
      middle_name:
        example: Doe
        type: string
    required:
    - first_name
    - last_name
    - middle_name
    type: object
  model.User:
    properties:
      active:
        example: true
        type: boolean
      address:
        $ref: '#/definitions/model.Address'
      created_at:
        example: "2024-07-27T00:00:00Z"
        type: string
      created_by:
        example: admin
        type: string
      deleted_at:
        example: "2024-07-27T00:00:00Z"
        type: string
      deleted_by:
        example: admin
        type: string
      email:
        example: vishal
        type: string
      id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      name:
        $ref: '#/definitions/model.Name'
      password:
        example: password
        type: string
      updated_at:
        example: "2024-07-27T00:00:00Z"
        type: string
      updated_by:
        example: admin
        type: string
    required:
    - address
    - created_by
    - email
    - name
    - password
    type: object
host: localhost:8000
info:
  contact: {}
  description: API for managing school
  title: User API
  version: "1.0"
paths:
  /user/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Get a user by ID
      tags:
      - users
  /user/all:
    get:
      parameters:
      - description: 'Page number (default: 1)'
        in: query
        name: page
        type: integer
      - description: 'Number of results per page (default: 10)'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: Get all users
      tags:
      - users
  /user/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
      summary: Create a user
      tags:
      - users
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Token
    type: apiKey
swagger: "2.0"
